// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:coffe_shop/core/utils/api_keys.dart';
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions android = FirebaseOptions(
    apiKey: ApiKeys.googleApiKeyAndroid,
    appId: '1:947579703019:android:b61d29e19e1c7b5e2a78ae',
    messagingSenderId: '947579703019',
    projectId: 'coffe-shop-f3918',
    storageBucket: 'coffe-shop-f3918.appspot.com',
  );

  static  FirebaseOptions ios = FirebaseOptions(
    apiKey: ApiKeys.googleApiKeyIos,
    appId: '1:947579703019:ios:e92db2a9e1b096772a78ae',
    messagingSenderId: '947579703019',
    projectId: 'coffe-shop-f3918',
    storageBucket: 'coffe-shop-f3918.appspot.com',
    iosBundleId: 'com.example.coffeShop',
  );
}
